repo_url: https://pedroaluciano.github.io/REQ-TEST/
repo_name: REQ-TEST


site_name: Meu Capilar

nav:
   - Home: index.md
   - Visão do produto e projeto:
      - Cenário atual do cliente e do negócio: unidade1/sessao1.md
      - Solução proposta: unidade1/sessao2.md
      

theme:
   name: material 
   palette:
    - scheme: default
      toggle: 
         icon: material/toggle-switch-off-outline
         name: Dark mode
      primary: brown
    - scheme: slate
      toggle:
         icon: material/toggle-switch
         name: Light mode
      primary: brown