site_name: Meu Capilar
site_url: https://mdsreq-fga-unb.github.io/2025.1-T02-MeuCapilar/
nav: 
 - Home: 'index.md'
 - Requisitos: 'requisitos.md'

 - Vis찾o de produto e projeto: 
    - Arquitetura: 'aarchitecture.md'
    - Vis찾o de produto: 'product.md'
    - Vis찾o de projeto: 'project.md'
 - Backlog: 'backlog.md'
 - Padr천es de desenvolvimento: 'patterns.md'

theme:
  name: material
  language: pt
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

